[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
debug_tool = esp-builtin
lib_deps =
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/Adafruit MPU6050@^2.2.4
    mikalhart/TinyGPSPlus@^1.0.3
    bblanchon/ArduinoJson@^7.0.3

[env:relay_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
src_dir = sketches
debug_tool = esp-builtin